apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
data:
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: glovo-talk-auth-aws-credentials
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID    
    name: demo-secrets           
    key: AWS_ACCESS_KEY_ID       
  - parameter: awsSecretAccessKey
    name: demo-secrets        
    key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: glovo-talk-scaledobject
  namespace: default
spec:
  maxReplicaCount: 6
  minReplicaCount: 0
  scaleTargetRef:
    kind: Deployment
    name: glovo-talk-deployment
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: glovo-talk-auth-aws-credentials
    metadata:
      awsRegion: <AWS_REGION>
      queueLength: "2"
      queueURL: <QUEUE_URL>
